<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Usaditos2026.BD\Usaditos2026.BD.csproj" />
    <ProjectReference Include="..\Usaditos2026.Shared\Usaditos2026.Shared.csproj" />
  </ItemGroup>

</Project>
